services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetstage_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - projetstage

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: projetstage_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - projetstage

  postgres:
    image: postgres:16
    container_name: projetstage_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: projetstage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projetstage

  mailhog:
    image: mailhog/mailhog:latest
    container_name: projetstage_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - projetstage

networks:
  projetstage:
    driver: bridge

volumes:
  postgres_data: